blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^connection/', include('connection.urls', namespace='connection')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^.*', include('main.urls')),
]

blog/order/urls.py
from django.conf.urls import url
from order import views

urlpatterns = [
    url(r'^$', views.order, name='order'),
    url(r'^orderCreate/$', views.orderCreate, name='orderCreate'),
]

blog/order/models.py
from django.db import models

# Create your models here.
class Order(models.Model):
    title = models.CharField(max_length=128)
    phone = models.CharField(max_length=128)
    paper = models.CharField(max_length=128)
    page = models.CharField(max_length=128)
    way = models.CharField(max_length=128)    
    content = models.TextField()

    
    
    def __str__(self):
        return self.title

blog/order/forms.py
from django import forms
from order.models import Order


class OrderForm(forms.ModelForm):
    title = forms.CharField(label='姓名', max_length=128)
    phone = forms.CharField(label='電話', max_length=128)
    paper= forms.CharField(label='紙張種類', max_length=128)
    page = forms.CharField(label='頁數', max_length=128)
    way = forms.CharField(label='裝訂方式', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)
    
    class Meta:   
        model = Order
        fields = ['title', 'phone', 'paper' , 'page' , 'way'  , 'content']
    #   

blog/order/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from order.forms import OrderForm
from order.models import Order
from django.contrib.auth.decorators import login_required


# Create your views here.
def order(request):
    '''
    Render the order page
    '''
    return render(request, 'order/order.html')

@login_required
def orderCreate(request):
    '''
    Create a new article instance
        1. If method is GET, render an empty form
        2 . If method is POST, perform form validation. Display error messages if the form is invalid
        3. Save the form to the model and redirect to the article page
    '''
    template = 'order/orderCreate.html'
    if request.method == 'GET':
        print(OrderForm())
        return render(request, template, {'orderForm':OrderForm()})
    # POST
    orderForm = OrderForm(request.POST)
    if not orderForm.is_valid():
        return render(request, template, {'orderForm':orderForm})
    orderForm.save()
    messages.success(request, '訂單已傳送')
    return redirect('order:order')

blog/order/templates/order/order.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/topmenu.html' %}
{% include 'main/menu.html' %}
<h1>訂單</h1>
{% for message in messages %}
  <p {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
{% endfor %}
<p><a class="btnn" href="{% url 'order:orderCreate' %}">新增訂單</a></p>
</body>
</html>

blog/order/templates/order/orderCreate.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>訂單系統</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/topmenu.html' %}
{% include 'main/menu.html' %}
<h2>新增訂單</h2>
{% for message in messages %}
  <p {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
{% endfor %}
<form method="post" action="{% url 'order:orderCreate' %}">
  {% csrf_token %}
  <table>
    {{ orderForm.as_table }}
  </table>
  <input class="btnn" type="submit" value="送出">
  <a class="btnn" href="{% url 'order:order' %}">放棄</a>
</form>
</body>
</html>