blog/account/urls.py
from django.conf.urls import url
from account import views


urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^connection/', include('connection.urls', namespace='connection')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^.*', include('main.urls')),
]

blog/connection/urls.py
from django.conf.urls import url
from connection import views

urlpatterns = [
    url(r'^$', views.connection, name='connection'),
]

blog/main/urls.py
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^about/$', views.about, name='about'),
    url(r'^mainCreate/$', views.mainCreate, name='mainCreate'),
    url(r'^mainRead/(?P<mainId>[0-9]+)/$', views.mainRead, name='mainRead'),
    url(r'^mainUpdate/(?P<mainId>[0-9]+)/$', views.mainUpdate, name='mainUpdate'),
    url(r'^mainSearch/$', views.mainSearch, name='mainSearch'),
]

blog/order/urls.py
from django.conf.urls import url
from order import views

urlpatterns = [
    url(r'^$', views.order, name='order'),
    url(r'^orderCreate/$', views.orderCreate, name='orderCreate'),
]

blog/main/models.py
from django.db import models

# Create your models here.
class Main(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-pubDateTime']

blog/main/forms.py
from django import forms
from main.models import Main
class MainForm(forms.ModelForm):
    title = forms.CharField(label='標題', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)
    
    
    class Meta:
        model = Main
        fields = ('title', 'content')

blog/main/views.py
from django.shortcuts import render, redirect, get_object_or_404 
from main.models import Main
from main.forms import MainForm
from django.contrib import messages
from connection.views import admin_required
from django.db.models.query_utils import Q
import datetime

def main(request):
    '''
    Show "Hello world" in the main page
    '''
    mains = Main.objects.all()
    itemsList = []
    for main in mains:
        items = [main]
        itemsList.append(items)
    context = {'itemsList':itemsList}
    return render(request, 'main/main.html', context)

def about(request):
    '''
    Render the about page
    '''
    return render(request, 'main/about.html')

@admin_required
def mainCreate(request):
    '''
    Create a new article instance
        1. If method is GET, render an empty form
        2 . If method is POST, perform form validation. Display error messages if the form is invalid
        3. Save the form to the model and redirect to the article page
    '''
    template = 'main/mainCreateUpdate.html'
    if request.method == 'GET':
        print(MainForm())
        return render(request, template, {'mainForm':MainForm()})
    # POST
    mainForm = MainForm(request.POST)
    if not mainForm.is_valid():
        return render(request, template, {'mainForm':mainForm})
    mainForm.save()
    messages.success(request, '最新消息已新增')
    return redirect('main:main')


def mainRead(request, mainId):
    '''
    Read an article
        1. Get the "article" instance using "articleId"; redirect to the 404 page if not found
        2. Render the articleRead template with article instance and its
    associated comments
    '''
    mainToRead = get_object_or_404(Main, id=mainId)
    context = {
        'main': mainToRead,
    }
    return render(request, 'main/mainRead.html', context)

@admin_required
def mainUpdate(request, mainId):
    '''
    Update the article instance:
        1. Get the article to update; redirect to 404 if not found
        2. Render a bound form if the method is GET
        3. If the form is valid, save it to the model, otherwise render a
    bound form with error messages
    '''
    mainToUpdate = get_object_or_404(Main, id=mainId)
    template = 'main/mainCreateUpdate.html'
    if request.method == 'GET':
        mainForm = MainForm(instance=mainToUpdate)
        return render(request, template, {'mainForm':mainForm, 'main':mainToUpdate})
    # POST
    mainForm = MainForm(request.POST, instance=mainToUpdate)
    if not mainForm.is_valid():
        return render(request, template, {'mainForm':mainForm, 'main':mainToUpdate})
    mainForm.save()
    messages.success(request, '最新消息已修改')
    return redirect('main:mainRead', mainId=mainId)


def mainSearch(request):
    '''
    Search for articles:
        1. Get the "searchTerm" from the HTML page
        2. Use "searchTerm" for filtering
    '''
    searchTerm = request.GET.get('searchTerm')
    mains = Main.objects.filter(Q(title__icontains=searchTerm) |
                                Q(content__icontains=searchTerm))
    context = {'mains':mains, 'searchTerm':searchTerm}
    return render(request, 'main/mainSearch.html', context)

blog/main/templates/main/about.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/topmenu.html' %}
{% include 'main/menu.html' %}
<h1>關於唐采</h1>
<figure>
  <img src=/img/cp1.jpg ></img><br>
  <figcaption>唐采印刷成立於1992年，以嚴格的品管與專業的技術，為客戶要求的優質產品提供了最佳保障。
  唐采印刷20多年來，精益求精，不斷的進步，不斷的添購設備，擴大廠房，開拓新市場，這表示我們是絕對不停滯，勇於創新。
  唐采印刷，以堅實的技術水準及設備自動化、一貫化及配合數位化，並堅持不變的原則就是『誠信經營』，唐采用誠心換信心與您交心。
  </figcaption>
</figure>
</body>
</html>

blog/main/templates/main/contact.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h2>聯絡我們</h2>
<p>123</p>
</body>
</html>

blog/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>唐采印刷</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="stylesheet" href="{% static 'main/css/hi.css' %}">
</head>
<body>
{% include 'main/topmenu.html' %}
{% include 'main/menu.html' %}
<h1>最新消息</h1>
{% for message in messages %}
  <p {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
{% endfor %}
{% include 'main/searchForm.html' %}
{% if user.is_superuser %}
  <p class="inlineBlock"><a class="btnn" href="{% url 'main:mainCreate' %}">新增最新消息</a></p>
{% endif %}
<br><br><hr>
{% for items in itemsList %}
  {% for item in items %}
    {% if forloop.first %}
      <h2><a href="{% url 'main:mainRead' item.id %}">{{ item.title }}</a></h2>
      <p>發表時間:{{ item.pubDateTime|date:'Y-m-d H:i' }}</p>
      <div class=mainContent>{{ item.content|linebreaks|truncatechars_html:30 }}</div>
    {% endif %}
  {% endfor %}
<hr>
{% endfor %}
</body>
</html>

blog/main/templates/main/mainCreateUpdate.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/topmenu.html' %}
{% include 'main/menu.html' %}
{% if main %}
  <h3>修改最新消息</h3>
  <form method="post" action="{% url 'main:mainUpdate' main.id %}">
{% else %}
  <h3>新增最新消息</h3>
  <form method="post" action="{% url 'main:mainCreate' %}">
{% endif %}  
  {% csrf_token %}
  {{ mainForm.as_p }}
<input class="btnn" type="submit" value="送出">
<a class="btnn" href="{% url 'main:main' %}">放棄</a>
</form>
</body>
</html>

blog/main/templates/main/mainRead.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
<link rel="stylesheet" href="{% static 'main/css/hi.css' %}">
</head>
<body>
{% include 'main/topmenu.html' %}
{% include 'main/menu.html' %}
{% for message in messages %}
  <p {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</p>
{% endfor %}
<h3 class="inlineBlock">{{ main.title }}</h3>
{% if user.is_superuser %}
  <a class="btnn inlineBlock" href="{% url 'main:mainUpdate' main.id %}">修改</a>
{% endif %}
<p>發表時間:{{ main.pubDateTime|date:'Y-m-d H:i' }}</p>
<div class=mainContent>{{ main.content|linebreaks }}</div>
</body>
</html>

blog/main/templates/main/mainSearch.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>最新消息</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h1>最新消息</h1>
{% include 'main/searchForm.html' %}
<br><br><hr>
{% if not mains %}
<p>查無資料</p>
{% else %}
  <table class="table table-striped table-hover">
    <tr><th>標題</th><th>發表時間</th></tr>
    {% for main in mains %}
    <tr>
      <td><a href="{% url 'main:mainRead' main.id %}">{{ main.title }}</a></td>
      <td>{{ main.pubDateTime|date:'Y-m-d H:i' }}</td>
    </tr>
    {% endfor %}
  </table>
{% endif %}
</body>
</html>

blog/main/templates/main/menu.html
<ul style='list-style-type:circle;'>
  <li><a class="btn" href="{% url 'main:main' %}">最新消息</a></li>
  <li><a class="btn" href="{% url 'main:about' %}">關於我們</a></li>
  <li><a class="btn" href="{% url 'connection:connection' %}">聯絡我們</a></li>
  <li><a class="btn" href="{% url 'order:order' %}">下單系統</a></li>
</ul>

blog/main/templates/main/searchForm.html
<form class="inlineBlock" action="{% url 'main:mainSearch' %}">
  <input type="text" name="searchTerm" {% if searchTerm %}value="{{ searchTerm }}"{% endif %}>
  <input class="btnn" type="submit" value="查詢">
</form>

blog/main/templates/main/topmenu.html
<dl style='list-style-type:circle;'>
  {% if user.is_authenticated %}
    <li><a href="{% url 'account:logout' %}">登出({{ user.username }})</a></li>
  {% else %}
    <li><a href="{% url 'account:register' %}">註冊</a></li>
    <li><a href="{% url 'account:login' %}">登入</a></li>
  {% endif %}
</dl>